package model

import (
	"gorm.io/gorm"
	"time"
)

type Project struct {
	gorm.Model
	Url      string
	Owner    string
	Repo     string
	Mode     int //0 monitors release, 1 monitors database
	Language string
	Command  string //Compilation command
	Suite    StrArr
	Pause    bool

	LastAnalyzeTime           time.Time
	LastAnalyzeReleaseTag     string
	LastAnalyzeDatabaseCommit string

	LatestVersion           string
	LatestVersionErrorInfo  string //If the version acquisition fails, it is used to save the failure information.
	LatestVersionUpdateTime time.Time
	LatestVersionCheckTime  time.Time
	LatestVersionCheckMode  int
}

type Setting struct {
	ID uint `gorm:"primarykey"`

	CodeQLCli      string
	CodeQLLib      string
	CodeQLPacks    string
	CodeQLSuite    string
	CodeQLDatabase string
	CodeQLResult   string
	EnvStr         string

	SystemToken string
	GithubToken string

	UpdateDetectionInterval float32 //Minimum interval for project update detection
	SkipVerifyTLS           bool

	AutoRecoveryTask  bool
	FirstReleaseCount int //When scanning releases for the first time, how many versions can be scanned at most?
	CronTaskSpec      string
	CronTaskNextTime  time.Time `gorm:"-"`

	AutoReadEmptyTask      bool
	AutoReadNoResultTask   bool
	AutoReadCompletedTask  bool
	AutoReadNoResultResult bool

	CodeQLAnalyzeOptions string
}

type Task struct {
	gorm.Model
	Status int    //0-in queue, 1-in progress, 2-completed, -1-error
	Stage  int    //0-Judge whether there is a new version, 1-Download the new version, 2-Compile the database, 3-Analyze
	Logs   string //summary log
	Manual bool   //Is it triggered manually?

	ProjectID       uint
	ProjectOwner    string
	ProjectRepo     string
	ProjectName     string
	ProjectLanguage string
	ProjectMode     int //0 monitors release, 1 monitors database
	ProjectCommand  string
	ProjectSuite    StrArr

	Versions         StrArr
	AnalyzedVersions StrArr

	TotalResultsCount int //The total number of vulnerabilities generated by this task

	IsRead bool
}

type TaskResult struct {
	gorm.Model
	Version     string
	Commit      string
	FileName    string
	ResultCount int
	IsRead      bool

	TaskId uint
	Task   Task

	CodeQLSarif interface{} `gorm:"-"`
	FilePath    string      `gorm:"-"`
}

type Status struct {
	ID uint `gorm:"primarykey"`

	TotalTasks     int64
	CompletedTasks int64
	FailedTasks    int64
	TotalResults   int64
}
